ultravideo/kvazaar

- src/Makefile
Unbreak building on MacOSX and possibly other BSDs.
> build: Drop the gnu-only option Deterministic

- src/Makefile
Links kvazaar against the shared library when building with `make LINK_SHARED=1` so you don't have to edit the Makefile if you prefer that.
> Make dynamic linking easier

- .gitignore
- autogen.sh
- configure.ac
- m4/ax_pthread.m4
`AC_PROG_CC_C99`: checks whether the compiler understands `-std=gnu99`, `-std=c99` or something else.
`AX_PTHREAD`: adds the appropriate pthread flags.
`AC_SEARCH_LIBS`: checks if -lm or -lc contain `log`/`pow`/`sqrt` and adds them to `LIBS` if needed (turns out that the ming32 compilers on my system don't even need `-lm`).
> check for c99, pthread and math library

- src/global.h
- tools/version.sh
Fixes regression since 54f08f2 causing libkvazaar version checks to not
work (i.e. pkg-config)
Fixes https://github.com/jb-alvarado/media-autobuild_suite/issues/298
> Only use version prefix in kvazaar binary

- src/global.h
x86_64-pc-linux-gnu-gcc -m32 that I use for building 32bits libraries on amd64 defines only __i386__.
> Include i386 & i486 for compiling intel asm.

- configure.ac
./configure --with-cryptopp failed while cross-compiling for an ARM target and this fixed it.
> Change some configure.ac library searching order.

- tests/Makefile.am
- tests/test_external_symbols.sh
- tests/test_gop.sh
- tests/test_interlace.sh
- tests/test_intra.sh
- tests/test_invalid_input.sh
- tests/test_mv_constraint.sh
- tests/test_owf_wpp_tiles.sh
- tests/test_rate_control.sh
- tests/test_slices.sh
- tests/test_smp.sh
- tests/test_tools.sh
- tests/test_weird_shapes.sh
- tests/util.sh
Regressed by 674af752a2bd:
- `/bin/bash` is distribution-specific, never happens on BSDs
- bash may not be installed or emulated by zsh
- `set -o pipefail` is bash-specific, the rest runs fine on zsh or (d)ash
- `mktemp --tmpdir` is GNU-specific but unrelated to bash
> Unbreak `make check` on FreeBSD

- configure.ac
cryptopp in version 6.1.0 added a pkg config file which is named libcryptopp.pc
so search also for this name in addition to cryptopp and libcrypto++
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> Check also for libcryptopp.pc in configure.ac

- Dockerfile
Ubuntu 15.10 was dated for a long time, and we can't build the Docker image without additional tweaking to manually set the apt repository to specified-old ones, moving to the LTS version which has 5-year support rather than 9-month would be a wise choice :)
> Update Dockerfile base image to Ubuntu 18.04

- src/strategyselector.c
FreeBSD can detect AltiVec via `hw.cpu_features` or `hw.altivec` sysctls. Other systems can check if  `-maltivec` is part of system CFLAGS e.g.,
```
$ clang -dM -E -</dev/null -target powerpc64-unknown-netbsd7.1 | fgrep -i altivec
#define __ALTIVEC__ 1
```
> Unbreak build on non-Linux powerpc*

- src/strategyselector.c
Blind follow up to #205. `MACOS` [isn't defined](https://github.com/llvm-mirror/clang/blob/ddb77a4e35a6/lib/Basic/Targets/OSTargets.cpp) on... macOS. 31c5ff0f160e probably tried to use `hw.ncpu` before finding more portable `_SC_NPROCESSORS_ONLN`.
> Clean up macOS includes in src/strategyselector.c

- src/strategyselector.c
Poking `/proc/self/auxv` isn't efficient compared to `getauxval()` which returns cached value. FreeBSD 12.0 (or later) has something similar.
> Switch AltiVec on Linux to getauxval()

- configure.ac
midipix is a new POSIX compatibility layer similar to cygwin.
> include support for midipix

- Dockerfile
Reference:
- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get
> Official Debian and Ubuntu images automatically run `apt-get clean`,
> so explicit invocation is not required.
> Remove additional apt-get clean in Dockerfile

- src/Makefile.am
Fixes a nuisance warning from `autogen.sh`:
```
src/Makefile.am:57: warning: whitespace following trailing backslash
```
> build: fix automake warning

- src/Makefile.am
When -mpopcnt or -mlzcnt are explicitly enable or disabled (when using -march=native for example), kvazaar builds fail on older CPUs without support for these flags (see https://github.com/ultravideo/kvazaar/issues/228 and https://bugs.gentoo.org/739776 ).
Ensuring these flags are on as done with the rest of AVX2 flags solves the compilation issues, although it may be a better approach to provide a configuration option so that only the specific version matching the build system supported flags is created in such cases.
> Enable -mpopcnt and -mlzcnt on AVX2

- src/cfg.c
- src/encoder.c
- src/kvazaar.c
- src/kvazaar.h
- src/strategyselector.c
- src/strategyselector.h
- tests/test_strategies.c
Added a new config option that can be used to turn off logging.
It only turns off status information like this:
````
Compiled: INTEL, flags: MMX SSE SSE2
Detected: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 AVX AVX2
Available: avx(11) avx2(54) sse2(2) sse41(4) 
In use: avx(1) avx2(54) 
--owf=auto value set to 2.
--threads=auto value set to 8.
````
Error messages are still shown on `stderr`.
> add config option to turn off logging output (#356)

- Dockerfile
Ubuntu 18.04 reached its end-of-life on May 31, 2023.
> Update Dockerfile base image to Ubuntu 20.04

- src/threads.h
This fixes the build for older macOS, including PowerPC.
(For the record, the build does require a newer `gcc` – archaic Xcode ones fail at configure.)
> threads.h: fix for older macOS builds

- src/extras/libmd5.c
Otherwise this fails the test which checks that all exported symbols begin with kvz_ prefix.
> Don't export MD5 byteReverse symbol on big-endian

- m4/ax_pthread.m4
clang also requires linking with -pthread to use pthreads. FFmpeg linking is broken otherwise due to undefined symbols.
Should remove the necessity of https://github.com/msys2/MINGW-packages/blob/5ed0594aee40d3df6437623c151b2a0e023634e1/mingw-w64-kvazaar/001-clang-pthread-fix.patch
> ax_pthread/clang: move -pthread to LIBS

- CMakeLists.txt
This PR fixes iOS builds.
On iOS it takes special care to build a executable, app bundle identifier are needed etc.
In a typical iOS build you only want to have the kvazaar lib to link with your app.
Because of that the option `-DBUILD_KVAZAAR_BINARY=OFF` is introduced to be able to build for iOS.
The build error looked like this:
```
cmake -G Xcode \
-DBUILD_SHARED_LIBS=OFF \
-DCMAKE_TOOLCHAIN_FILE=./ios.toolchain.cmake \
-DPLATFORM=OS64 \
-DBUILD_TESTS=OFF \
-DCMAKE_BUILD_TYPE=Release \
.. \
&& \
xcodebuild -project kvazaar.xcodeproj \
-scheme install \
-configuration Release \
-quiet \
-allowProvisioningUpdates \
-destination generic/platform=iOS \
-derivedDataPath ./build \
build
. . .
-- Configuring done
-- Generating done
-- Build files have been written to: …
```
> fix ios build

- CMakeLists.txt
- tests/CMakeLists.txt
This PR provides build fixes for Android.
The android build got broken in version 2.3.1.
In 2.3.0 it worked fine.
There are two build errors that are fixed with this PR for Android NDK builds:
1. Threads
```
CMake Error at /opt/homebrew/Cellar/cmake/3.25.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find Threads (missing: Threads_FOUND)
```
2. muse-unaligned-vector-move
```
sventrittler@Svens-MBP b % cmake --build .
[  1%] Building C object CMakeFiles/kvazaar.dir/src/bitstream.c.o
clang: error: unsupported argument '-muse-unaligned-vector-move' to option 'Wa,'
```
May android builds should be added to the CI some day.
> fix android build

- .gitignore
- src/encoder.c
* Copy the `file_path` string after `memcpy` of `cfg`.
* Closes #427 
* Check if the same change is needed for `optional_key` and `fastrd_learning_outdir_fn`.
> Avoid double free of roi.file_path
